language: cpp
compiler:
    - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'versioninfo(); Pkg.clone(pwd())'
    - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'Pkg.test("GLM"; coverage=true)'; fi
    - if [ $JULIAVERSION = "juliareleases" ]; then julia -e 'Pkg.test("GLM")'; fi
after_success:
    - if [ $JULIAVERSION = "juliareleases" ]; then julia -e 'cd(Pkg.dir("GLM")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
